# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'testium_core_win.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDockWidget, QFrame,
    QHBoxLayout, QLabel, QLayout, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTextEdit, QToolBar,
    QToolButton, QVBoxLayout, QWidget)
import testium_core_win_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1081, 730)
        icon = QIcon()
        icon.addFile(u":/black/testium_logo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.actionOpenTest = QAction(MainWindow)
        self.actionOpenTest.setObjectName(u"actionOpenTest")
        icon1 = QIcon()
        icon1.addFile(u":/black/document-open.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenTest.setIcon(icon1)
        self.actionSave_report = QAction(MainWindow)
        self.actionSave_report.setObjectName(u"actionSave_report")
        icon2 = QIcon()
        icon2.addFile(u":/black/document-save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave_report.setIcon(icon2)
        self.actionStart_test = QAction(MainWindow)
        self.actionStart_test.setObjectName(u"actionStart_test")
        icon3 = QIcon()
        icon3.addFile(u":/black/start.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStart_test.setIcon(icon3)
        self.actionStop_test = QAction(MainWindow)
        self.actionStop_test.setObjectName(u"actionStop_test")
        self.actionStop_test.setEnabled(False)
        icon4 = QIcon()
        icon4.addFile(u":/black/stop.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStop_test.setIcon(icon4)
        self.actionStep_over = QAction(MainWindow)
        self.actionStep_over.setObjectName(u"actionStep_over")
        self.actionStep_over.setEnabled(False)
        icon5 = QIcon()
        icon5.addFile(u":/black/step-over.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStep_over.setIcon(icon5)
        self.actionStep_into = QAction(MainWindow)
        self.actionStep_into.setObjectName(u"actionStep_into")
        self.actionStep_into.setEnabled(False)
        icon6 = QIcon()
        icon6.addFile(u":/black/step-into.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStep_into.setIcon(icon6)
        self.actionStep_out = QAction(MainWindow)
        self.actionStep_out.setObjectName(u"actionStep_out")
        self.actionStep_out.setEnabled(False)
        icon7 = QIcon()
        icon7.addFile(u":/black/step-out.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStep_out.setIcon(icon7)
        self.actionDebugOutput = QAction(MainWindow)
        self.actionDebugOutput.setObjectName(u"actionDebugOutput")
        self.actionDebugOutput.setCheckable(True)
        icon8 = QIcon()
        icon8.addFile(u":/black/bug.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDebugOutput.setIcon(icon8)
        self.actionAbout_testium = QAction(MainWindow)
        self.actionAbout_testium.setObjectName(u"actionAbout_testium")
        icon9 = QIcon()
        icon9.addFile(u":/black/about.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbout_testium.setIcon(icon9)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon10 = QIcon()
        icon10.addFile(u":/black/exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit.setIcon(icon10)
        self.actionRefresh_test = QAction(MainWindow)
        self.actionRefresh_test.setObjectName(u"actionRefresh_test")
        icon11 = QIcon()
        icon11.addFile(u":/black/view-refresh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRefresh_test.setIcon(icon11)
        self.actionShow_Results = QAction(MainWindow)
        self.actionShow_Results.setObjectName(u"actionShow_Results")
        icon12 = QIcon()
        icon12.addFile(u":/black/results.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionShow_Results.setIcon(icon12)
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        icon13 = QIcon()
        icon13.addFile(u":/black/help.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHelp.setIcon(icon13)
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        icon14 = QIcon()
        icon14.addFile(u":/black/settings.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPreferences.setIcon(icon14)
        self.actionTestInformation = QAction(MainWindow)
        self.actionTestInformation.setObjectName(u"actionTestInformation")
        icon15 = QIcon()
        icon15.addFile(u":/black/info.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTestInformation.setIcon(icon15)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.horizontalLayout_8 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.centralColumn = QWidget(self.centralwidget)
        self.centralColumn.setObjectName(u"centralColumn")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralColumn.sizePolicy().hasHeightForWidth())
        self.centralColumn.setSizePolicy(sizePolicy1)
        self.centralColumn.setMinimumSize(QSize(100, 0))
        self.centralColumn.setBaseSize(QSize(0, 0))
        self.verticalLayout = QVBoxLayout(self.centralColumn)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.controlRow = QWidget(self.centralColumn)
        self.controlRow.setObjectName(u"controlRow")
        sizePolicy1.setHeightForWidth(self.controlRow.sizePolicy().hasHeightForWidth())
        self.controlRow.setSizePolicy(sizePolicy1)
        self.horizontalLayout_2 = QHBoxLayout(self.controlRow)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.controlRow)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy2)
#if QT_CONFIG(accessibility)
        self.frame_3.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setSizeConstraint(QLayout.SetMinimumSize)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.checkSelect = QCheckBox(self.frame_3)
        self.checkSelect.setObjectName(u"checkSelect")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.checkSelect.sizePolicy().hasHeightForWidth())
        self.checkSelect.setSizePolicy(sizePolicy3)
        self.checkSelect.setChecked(True)
        self.checkSelect.setTristate(False)

        self.horizontalLayout_9.addWidget(self.checkSelect)

        self.checkFold = QCheckBox(self.frame_3)
        self.checkFold.setObjectName(u"checkFold")

        self.horizontalLayout_9.addWidget(self.checkFold)

        self.label_runtime = QLabel(self.frame_3)
        self.label_runtime.setObjectName(u"label_runtime")
        sizePolicy2.setHeightForWidth(self.label_runtime.sizePolicy().hasHeightForWidth())
        self.label_runtime.setSizePolicy(sizePolicy2)
        self.label_runtime.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_9.addWidget(self.label_runtime)

        self.buttBlink = QPushButton(self.frame_3)
        self.buttBlink.setObjectName(u"buttBlink")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.buttBlink.sizePolicy().hasHeightForWidth())
        self.buttBlink.setSizePolicy(sizePolicy4)
        self.buttBlink.setStyleSheet(u"QPushButton {\n"
"                border-width: 1px;\n"
" 				border-style: solid;\n"
" }")
        icon16 = QIcon()
        icon16.addFile(u":/black/green.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttBlink.setIcon(icon16)
        self.buttBlink.setIconSize(QSize(28, 28))
        self.buttBlink.setFlat(True)

        self.horizontalLayout_9.addWidget(self.buttBlink)


        self.horizontalLayout_2.addWidget(self.frame_3, 0, Qt.AlignTop)


        self.verticalLayout.addWidget(self.controlRow)


        self.horizontalLayout_8.addWidget(self.centralColumn)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setLayoutDirection(Qt.LeftToRight)
        self.toolBar.setIconSize(QSize(24, 24))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1081, 30))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuTest = QMenu(self.menuBar)
        self.menuTest.setObjectName(u"menuTest")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuA_propos = QMenu(self.menuBar)
        self.menuA_propos.setObjectName(u"menuA_propos")
        MainWindow.setMenuBar(self.menuBar)
        self.logDockWidget = QDockWidget(MainWindow)
        self.logDockWidget.setObjectName(u"logDockWidget")
        self.logDockWidget.setFeatures(QDockWidget.DockWidgetClosable|QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.logDockWidget.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.horizontalLayout_7 = QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.logFrame = QFrame(self.dockWidgetContents)
        self.logFrame.setObjectName(u"logFrame")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.logFrame.sizePolicy().hasHeightForWidth())
        self.logFrame.setSizePolicy(sizePolicy5)
        self.verticalLayout_3 = QVBoxLayout(self.logFrame)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.logHeaderRow = QHBoxLayout()
        self.logHeaderRow.setSpacing(4)
        self.logHeaderRow.setObjectName(u"logHeaderRow")
        self.logSettingsBox = QFrame(self.logFrame)
        self.logSettingsBox.setObjectName(u"logSettingsBox")
        self.horizontalLayout_5 = QHBoxLayout(self.logSettingsBox)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.buttLogFileSaved = QCheckBox(self.logSettingsBox)
        self.buttLogFileSaved.setObjectName(u"buttLogFileSaved")

        self.horizontalLayout_5.addWidget(self.buttLogFileSaved)

        self.editLogFilePath = QLineEdit(self.logSettingsBox)
        self.editLogFilePath.setObjectName(u"editLogFilePath")

        self.horizontalLayout_5.addWidget(self.editLogFilePath)

        self.buttLogFilePath = QToolButton(self.logSettingsBox)
        self.buttLogFilePath.setObjectName(u"buttLogFilePath")

        self.horizontalLayout_5.addWidget(self.buttLogFilePath)


        self.logHeaderRow.addWidget(self.logSettingsBox)

        self.buttClearLog = QToolButton(self.logFrame)
        self.buttClearLog.setObjectName(u"buttClearLog")
        icon17 = QIcon()
        icon17.addFile(u":/black/edit-clear.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttClearLog.setIcon(icon17)

        self.logHeaderRow.addWidget(self.buttClearLog)

        self.buttGoBottom = QToolButton(self.logFrame)
        self.buttGoBottom.setObjectName(u"buttGoBottom")
        icon18 = QIcon()
        icon18.addFile(u":/black/go-bottom.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttGoBottom.setIcon(icon18)

        self.logHeaderRow.addWidget(self.buttGoBottom)


        self.verticalLayout_3.addLayout(self.logHeaderRow)

        self.logViewFrame = QFrame(self.logFrame)
        self.logViewFrame.setObjectName(u"logViewFrame")
        self.verticalLayout_2 = QVBoxLayout(self.logViewFrame)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)

        self.verticalLayout_3.addWidget(self.logViewFrame)


        self.horizontalLayout_7.addWidget(self.logFrame)

        self.logDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.logDockWidget)
        self.DocDockWidget = QDockWidget(MainWindow)
        self.DocDockWidget.setObjectName(u"DocDockWidget")
        self.DocDockWidget.setEnabled(True)
        self.DocDockWidget.setFloating(False)
        self.DocDockWidget.setFeatures(QDockWidget.DockWidgetClosable|QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.horizontalLayout_10 = QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.textEditTestDoc = QTextEdit(self.dockWidgetContents_2)
        self.textEditTestDoc.setObjectName(u"textEditTestDoc")
        self.textEditTestDoc.setUndoRedoEnabled(False)
        self.textEditTestDoc.setReadOnly(True)

        self.horizontalLayout_10.addWidget(self.textEditTestDoc)

        self.DocDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.DocDockWidget)

        self.toolBar.addAction(self.actionOpenTest)
        self.toolBar.addAction(self.actionRefresh_test)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave_report)
        self.toolBar.addAction(self.actionShow_Results)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTest.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuA_propos.menuAction())
        self.menuFile.addAction(self.actionOpenTest)
        self.menuFile.addAction(self.actionRefresh_test)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTest.addAction(self.actionStart_test)
        self.menuTest.addAction(self.actionStop_test)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionDebugOutput)
        self.menuTest.addAction(self.actionStep_over)
        self.menuTest.addAction(self.actionStep_into)
        self.menuTest.addAction(self.actionStep_out)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionTestInformation)
        self.menuTest.addAction(self.actionSave_report)
        self.menuTest.addAction(self.actionShow_Results)
        self.menuTest.addSeparator()
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionPreferences)
        self.menuA_propos.addAction(self.actionAbout_testium)
        self.menuA_propos.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"testium", None))
        self.actionOpenTest.setText(QCoreApplication.translate("MainWindow", u"&Open Test", None))
#if QT_CONFIG(tooltip)
        self.actionOpenTest.setToolTip(QCoreApplication.translate("MainWindow", u"Open a test set", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave_report.setText(QCoreApplication.translate("MainWindow", u"&Save Results", None))
        self.actionSave_report.setIconText(QCoreApplication.translate("MainWindow", u"Save Results", None))
#if QT_CONFIG(tooltip)
        self.actionSave_report.setToolTip(QCoreApplication.translate("MainWindow", u"Save Results", None))
#endif // QT_CONFIG(tooltip)
        self.actionStart_test.setText(QCoreApplication.translate("MainWindow", u"Start test", None))
#if QT_CONFIG(tooltip)
        self.actionStart_test.setToolTip(QCoreApplication.translate("MainWindow", u"Start, pause or resume the test (F5)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionStart_test.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionStop_test.setText(QCoreApplication.translate("MainWindow", u"Stop test", None))
#if QT_CONFIG(tooltip)
        self.actionStop_test.setToolTip(QCoreApplication.translate("MainWindow", u"Stop the test (Shift+F5)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionStop_test.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionStep_over.setText(QCoreApplication.translate("MainWindow", u"Step over", None))
#if QT_CONFIG(tooltip)
        self.actionStep_over.setToolTip(QCoreApplication.translate("MainWindow", u"Run to the next item at the same level (F10)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionStep_over.setShortcut(QCoreApplication.translate("MainWindow", u"F10", None))
#endif // QT_CONFIG(shortcut)
        self.actionStep_into.setText(QCoreApplication.translate("MainWindow", u"Step into", None))
#if QT_CONFIG(tooltip)
        self.actionStep_into.setToolTip(QCoreApplication.translate("MainWindow", u"Pause on the next item, entering nested steps (F11). From idle: start the test paused on its first item.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionStep_into.setShortcut(QCoreApplication.translate("MainWindow", u"F11", None))
#endif // QT_CONFIG(shortcut)
        self.actionStep_out.setText(QCoreApplication.translate("MainWindow", u"Step out", None))
#if QT_CONFIG(tooltip)
        self.actionStep_out.setToolTip(QCoreApplication.translate("MainWindow", u"Run to the end of the current level, pause one level up (Shift+F11)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionStep_out.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+F11", None))
#endif // QT_CONFIG(shortcut)
        self.actionDebugOutput.setText(QCoreApplication.translate("MainWindow", u"Debug", None))
#if QT_CONFIG(tooltip)
        self.actionDebugOutput.setToolTip(QCoreApplication.translate("MainWindow", u"Debug output (Ctrl+Shift+D)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDebugOutput.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout_testium.setText(QCoreApplication.translate("MainWindow", u"About testium", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionRefresh_test.setText(QCoreApplication.translate("MainWindow", u"Refresh test", None))
        self.actionShow_Results.setText(QCoreApplication.translate("MainWindow", u"Show &Results", None))
#if QT_CONFIG(tooltip)
        self.actionShow_Results.setToolTip(QCoreApplication.translate("MainWindow", u"Show test results in external editor", None))
#endif // QT_CONFIG(tooltip)
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
#if QT_CONFIG(tooltip)
        self.actionHelp.setToolTip(QCoreApplication.translate("MainWindow", u"testium help", None))
#endif // QT_CONFIG(tooltip)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
#if QT_CONFIG(tooltip)
        self.actionPreferences.setToolTip(QCoreApplication.translate("MainWindow", u"Application parameters adjustment", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionPreferences.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionTestInformation.setText(QCoreApplication.translate("MainWindow", u"Step &Information", None))
#if QT_CONFIG(tooltip)
        self.actionTestInformation.setToolTip(QCoreApplication.translate("MainWindow", u"Details on the selected test step", None))
#endif // QT_CONFIG(tooltip)
        self.checkSelect.setText(QCoreApplication.translate("MainWindow", u"Select all / deselect all", None))
        self.checkFold.setText(QCoreApplication.translate("MainWindow", u"Fold / Unfold", None))
        self.label_runtime.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.buttBlink.setText("")
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuTest.setTitle(QCoreApplication.translate("MainWindow", u"&Test", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.menuA_propos.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.logDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Log", None))
        self.buttLogFileSaved.setText(QCoreApplication.translate("MainWindow", u"To file", None))
#if QT_CONFIG(tooltip)
        self.buttLogFileSaved.setToolTip(QCoreApplication.translate("MainWindow", u"Write the run log to the file beside", None))
#endif // QT_CONFIG(tooltip)
        self.editLogFilePath.setPlaceholderText(QCoreApplication.translate("MainWindow", u"log file path", None))
        self.buttLogFilePath.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.buttClearLog.setToolTip(QCoreApplication.translate("MainWindow", u"Clear the log view", None))
#endif // QT_CONFIG(tooltip)
        self.buttClearLog.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.buttGoBottom.setToolTip(QCoreApplication.translate("MainWindow", u"Go to the bottom of the log", None))
#endif // QT_CONFIG(tooltip)
        self.buttGoBottom.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.DocDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Test doc", None))
    # retranslateUi

