# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'testium_core_win.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDockWidget, QFrame,
    QHBoxLayout, QLabel, QLayout, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QSpacerItem, QStatusBar,
    QTextEdit, QToolBar, QToolButton, QVBoxLayout,
    QWidget)
import testium_core_win_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1081, 730)
        font = QFont()
        font.setFamilies([u"Sans"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/black/testium_logo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.actionOpenTest = QAction(MainWindow)
        self.actionOpenTest.setObjectName(u"actionOpenTest")
        icon1 = QIcon()
        icon1.addFile(u":/black/document-open.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenTest.setIcon(icon1)
        self.actionSave_report = QAction(MainWindow)
        self.actionSave_report.setObjectName(u"actionSave_report")
        icon2 = QIcon()
        icon2.addFile(u":/black/document-save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave_report.setIcon(icon2)
        self.actionStart_test = QAction(MainWindow)
        self.actionStart_test.setObjectName(u"actionStart_test")
        icon3 = QIcon()
        icon3.addFile(u":/black/start.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStart_test.setIcon(icon3)
        self.actionStop_test = QAction(MainWindow)
        self.actionStop_test.setObjectName(u"actionStop_test")
        self.actionStop_test.setEnabled(False)
        icon4 = QIcon()
        icon4.addFile(u":/black/stop.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStop_test.setIcon(icon4)
        self.actionStep_over = QAction(MainWindow)
        self.actionStep_over.setObjectName(u"actionStep_over")
        self.actionStep_over.setEnabled(False)
        icon5 = QIcon()
        icon5.addFile(u":/black/step-over.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStep_over.setIcon(icon5)
        self.actionStep_into = QAction(MainWindow)
        self.actionStep_into.setObjectName(u"actionStep_into")
        self.actionStep_into.setEnabled(False)
        icon6 = QIcon()
        icon6.addFile(u":/black/step-into.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStep_into.setIcon(icon6)
        self.actionStep_out = QAction(MainWindow)
        self.actionStep_out.setObjectName(u"actionStep_out")
        self.actionStep_out.setEnabled(False)
        icon7 = QIcon()
        icon7.addFile(u":/black/step-out.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStep_out.setIcon(icon7)
        self.actionAbout_testium = QAction(MainWindow)
        self.actionAbout_testium.setObjectName(u"actionAbout_testium")
        icon8 = QIcon()
        icon8.addFile(u":/black/about.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbout_testium.setIcon(icon8)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon9 = QIcon()
        icon9.addFile(u":/black/exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit.setIcon(icon9)
        self.actionRefresh_test = QAction(MainWindow)
        self.actionRefresh_test.setObjectName(u"actionRefresh_test")
        icon10 = QIcon()
        icon10.addFile(u":/black/view-refresh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRefresh_test.setIcon(icon10)
        self.actionShow_Results = QAction(MainWindow)
        self.actionShow_Results.setObjectName(u"actionShow_Results")
        icon11 = QIcon()
        icon11.addFile(u":/black/results.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionShow_Results.setIcon(icon11)
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        icon12 = QIcon()
        icon12.addFile(u":/black/help.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHelp.setIcon(icon12)
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        icon13 = QIcon()
        icon13.addFile(u":/black/settings.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPreferences.setIcon(icon13)
        self.actionTestInformation = QAction(MainWindow)
        self.actionTestInformation.setObjectName(u"actionTestInformation")
        icon14 = QIcon()
        icon14.addFile(u":/black/info.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTestInformation.setIcon(icon14)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.horizontalLayout_8 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        self.widget.setMinimumSize(QSize(100, 0))
        self.widget.setBaseSize(QSize(0, 0))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.widget1 = QWidget(self.widget)
        self.widget1.setObjectName(u"widget1")
        sizePolicy1.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy1)
        self.widget1.setMinimumSize(QSize(315, 0))
        self.horizontalLayout_2 = QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.widget1)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy2)
#if QT_CONFIG(accessibility)
        self.frame_3.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setSizeConstraint(QLayout.SetMinimumSize)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.checkSelect = QCheckBox(self.frame_3)
        self.checkSelect.setObjectName(u"checkSelect")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.checkSelect.sizePolicy().hasHeightForWidth())
        self.checkSelect.setSizePolicy(sizePolicy3)
        self.checkSelect.setMinimumSize(QSize(125, 0))
        self.checkSelect.setChecked(True)
        self.checkSelect.setTristate(False)

        self.horizontalLayout_9.addWidget(self.checkSelect)

        self.checkFold = QCheckBox(self.frame_3)
        self.checkFold.setObjectName(u"checkFold")

        self.horizontalLayout_9.addWidget(self.checkFold)

        self.label_runtime = QLabel(self.frame_3)
        self.label_runtime.setObjectName(u"label_runtime")
        sizePolicy2.setHeightForWidth(self.label_runtime.sizePolicy().hasHeightForWidth())
        self.label_runtime.setSizePolicy(sizePolicy2)
        self.label_runtime.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_9.addWidget(self.label_runtime)

        self.buttBlink = QPushButton(self.frame_3)
        self.buttBlink.setObjectName(u"buttBlink")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.buttBlink.sizePolicy().hasHeightForWidth())
        self.buttBlink.setSizePolicy(sizePolicy4)
        self.buttBlink.setStyleSheet(u"QPushButton {\n"
"                border-width: 1px;\n"
" 				border-style: solid;\n"
" }")
        icon15 = QIcon()
        icon15.addFile(u":/black/green.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttBlink.setIcon(icon15)
        self.buttBlink.setIconSize(QSize(28, 28))
        self.buttBlink.setFlat(True)

        self.horizontalLayout_9.addWidget(self.buttBlink)


        self.horizontalLayout_2.addWidget(self.frame_3, 0, Qt.AlignTop)


        self.verticalLayout.addWidget(self.widget1)


        self.horizontalLayout_8.addWidget(self.widget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setLayoutDirection(Qt.LeftToRight)
        self.toolBar.setIconSize(QSize(24, 24))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1081, 30))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuTest = QMenu(self.menuBar)
        self.menuTest.setObjectName(u"menuTest")
        self.menuA_propos = QMenu(self.menuBar)
        self.menuA_propos.setObjectName(u"menuA_propos")
        MainWindow.setMenuBar(self.menuBar)
        self.logDockWidget = QDockWidget(MainWindow)
        self.logDockWidget.setObjectName(u"logDockWidget")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.logDockWidget.sizePolicy().hasHeightForWidth())
        self.logDockWidget.setSizePolicy(sizePolicy5)
        font1 = QFont()
        font1.setFamilies([u"Sans"])
        font1.setPointSize(9)
        font1.setStyleStrategy(QFont.PreferAntialias)
        self.logDockWidget.setFont(font1)
        self.logDockWidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.logDockWidget.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        font2 = QFont()
        font2.setFamilies([u"Sans"])
        font2.setPointSize(10)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.dockWidgetContents.setFont(font2)
        self.horizontalLayout_7 = QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.frame = QFrame(self.dockWidgetContents)
        self.frame.setObjectName(u"frame")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy6)
        self.verticalLayout_3 = QVBoxLayout(self.frame)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.logSettingsBox = QFrame(self.frame)
        self.logSettingsBox.setObjectName(u"logSettingsBox")
        self.horizontalLayout_5 = QHBoxLayout(self.logSettingsBox)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.widget_6 = QWidget(self.logSettingsBox)
        self.widget_6.setObjectName(u"widget_6")
        self.verticalLayout_9 = QVBoxLayout(self.widget_6)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.buttLogFileNone = QRadioButton(self.widget_6)
        self.buttLogFileNone.setObjectName(u"buttLogFileNone")
        self.buttLogFileNone.setChecked(True)

        self.verticalLayout_9.addWidget(self.buttLogFileNone)

        self.buttLogFileSaved = QRadioButton(self.widget_6)
        self.buttLogFileSaved.setObjectName(u"buttLogFileSaved")

        self.verticalLayout_9.addWidget(self.buttLogFileSaved)


        self.horizontalLayout_5.addWidget(self.widget_6)

        self.horizontalSpacer_3 = QSpacerItem(10, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_3)

        self.widget_5 = QWidget(self.logSettingsBox)
        self.widget_5.setObjectName(u"widget_5")
        self.verticalLayout_8 = QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.widget_5)
        self.label.setObjectName(u"label")

        self.verticalLayout_8.addWidget(self.label)

        self.editLogFilePath = QLineEdit(self.widget_5)
        self.editLogFilePath.setObjectName(u"editLogFilePath")

        self.verticalLayout_8.addWidget(self.editLogFilePath)


        self.horizontalLayout_5.addWidget(self.widget_5)

        self.buttLogFilePath = QToolButton(self.logSettingsBox)
        self.buttLogFilePath.setObjectName(u"buttLogFilePath")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.buttLogFilePath.sizePolicy().hasHeightForWidth())
        self.buttLogFilePath.setSizePolicy(sizePolicy7)

        self.horizontalLayout_5.addWidget(self.buttLogFilePath)

        self.horizontalSpacer_4 = QSpacerItem(10, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_4)


        self.verticalLayout_3.addWidget(self.logSettingsBox)

        self.frame1 = QFrame(self.frame)
        self.frame1.setObjectName(u"frame1")
        self.verticalLayout_2 = QVBoxLayout(self.frame1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.widget_2 = QWidget(self.frame1)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout_4 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.widget_3 = QWidget(self.widget_2)
        self.widget_3.setObjectName(u"widget_3")
        self.verticalLayout_7 = QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)

        self.horizontalLayout_4.addWidget(self.widget_3)

        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        font3 = QFont()
        font3.setFamilies([u"Sans"])
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setStyleStrategy(QFont.PreferAntialias)
        self.label_2.setFont(font3)

        self.horizontalLayout_4.addWidget(self.label_2)

        self.widget_7 = QWidget(self.widget_2)
        self.widget_7.setObjectName(u"widget_7")
        self.horizontalLayout_6 = QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)

        self.horizontalLayout_4.addWidget(self.widget_7)

        self.horizontalSpacer_2 = QSpacerItem(40, 10, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_2)

        self.buttClearLog = QToolButton(self.widget_2)
        self.buttClearLog.setObjectName(u"buttClearLog")
        icon16 = QIcon()
        icon16.addFile(u":/black/edit-clear.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttClearLog.setIcon(icon16)

        self.horizontalLayout_4.addWidget(self.buttClearLog)

        self.buttGoBottom = QToolButton(self.widget_2)
        self.buttGoBottom.setObjectName(u"buttGoBottom")
        icon17 = QIcon()
        icon17.addFile(u":/black/go-bottom.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttGoBottom.setIcon(icon17)
        self.buttGoBottom.setCheckable(False)
        self.buttGoBottom.setChecked(False)
        self.buttGoBottom.setToolButtonStyle(Qt.ToolButtonIconOnly)

        self.horizontalLayout_4.addWidget(self.buttGoBottom)


        self.verticalLayout_2.addWidget(self.widget_2)


        self.verticalLayout_3.addWidget(self.frame1)


        self.horizontalLayout_7.addWidget(self.frame)

        self.logDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.logDockWidget)
        self.DocDockWidget = QDockWidget(MainWindow)
        self.DocDockWidget.setObjectName(u"DocDockWidget")
        self.DocDockWidget.setEnabled(True)
        self.DocDockWidget.setFloating(False)
        self.DocDockWidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.horizontalLayout_10 = QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.textEditTestDoc = QTextEdit(self.dockWidgetContents_2)
        self.textEditTestDoc.setObjectName(u"textEditTestDoc")
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(11)
        self.textEditTestDoc.setFont(font4)
        self.textEditTestDoc.setUndoRedoEnabled(False)
        self.textEditTestDoc.setReadOnly(True)

        self.horizontalLayout_10.addWidget(self.textEditTestDoc)

        self.DocDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.DocDockWidget)

        self.toolBar.addAction(self.actionOpenTest)
        self.toolBar.addAction(self.actionRefresh_test)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTestInformation)
        self.toolBar.addAction(self.actionSave_report)
        self.toolBar.addAction(self.actionShow_Results)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart_test)
        self.toolBar.addAction(self.actionStep_over)
        self.toolBar.addAction(self.actionStep_into)
        self.toolBar.addAction(self.actionStep_out)
        self.toolBar.addAction(self.actionStop_test)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTest.menuAction())
        self.menuBar.addAction(self.menuA_propos.menuAction())
        self.menuFile.addAction(self.actionOpenTest)
        self.menuFile.addAction(self.actionRefresh_test)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTest.addAction(self.actionStart_test)
        self.menuTest.addAction(self.actionStop_test)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionStep_over)
        self.menuTest.addAction(self.actionStep_into)
        self.menuTest.addAction(self.actionStep_out)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionTestInformation)
        self.menuTest.addAction(self.actionSave_report)
        self.menuTest.addAction(self.actionShow_Results)
        self.menuTest.addSeparator()
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionPreferences)
        self.menuA_propos.addAction(self.actionAbout_testium)
        self.menuA_propos.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"testium", None))
        self.actionOpenTest.setText(QCoreApplication.translate("MainWindow", u"&Open Test", None))
#if QT_CONFIG(tooltip)
        self.actionOpenTest.setToolTip(QCoreApplication.translate("MainWindow", u"Open a test set", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave_report.setText(QCoreApplication.translate("MainWindow", u"&Save Results", None))
        self.actionSave_report.setIconText(QCoreApplication.translate("MainWindow", u"Save Results", None))
#if QT_CONFIG(tooltip)
        self.actionSave_report.setToolTip(QCoreApplication.translate("MainWindow", u"Save Results", None))
#endif // QT_CONFIG(tooltip)
        self.actionStart_test.setText(QCoreApplication.translate("MainWindow", u"Start test", None))
        self.actionStop_test.setText(QCoreApplication.translate("MainWindow", u"Stop test", None))
        self.actionStep_over.setText(QCoreApplication.translate("MainWindow", u"Step over", None))
#if QT_CONFIG(tooltip)
        self.actionStep_over.setToolTip(QCoreApplication.translate("MainWindow", u"Run to the next item at the same level (F10)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionStep_over.setShortcut(QCoreApplication.translate("MainWindow", u"F10", None))
#endif // QT_CONFIG(shortcut)
        self.actionStep_into.setText(QCoreApplication.translate("MainWindow", u"Step into", None))
#if QT_CONFIG(tooltip)
        self.actionStep_into.setToolTip(QCoreApplication.translate("MainWindow", u"Pause on the next item, entering nested steps (F11). From idle: start the test paused on its first item.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionStep_into.setShortcut(QCoreApplication.translate("MainWindow", u"F11", None))
#endif // QT_CONFIG(shortcut)
        self.actionStep_out.setText(QCoreApplication.translate("MainWindow", u"Step out", None))
#if QT_CONFIG(tooltip)
        self.actionStep_out.setToolTip(QCoreApplication.translate("MainWindow", u"Run to the end of the current level, pause one level up (Shift+F11)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionStep_out.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+F11", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout_testium.setText(QCoreApplication.translate("MainWindow", u"About testium", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionRefresh_test.setText(QCoreApplication.translate("MainWindow", u"Refresh test", None))
        self.actionShow_Results.setText(QCoreApplication.translate("MainWindow", u"Show &Results", None))
#if QT_CONFIG(tooltip)
        self.actionShow_Results.setToolTip(QCoreApplication.translate("MainWindow", u"Show test results in external editor", None))
#endif // QT_CONFIG(tooltip)
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
#if QT_CONFIG(tooltip)
        self.actionHelp.setToolTip(QCoreApplication.translate("MainWindow", u"testium help", None))
#endif // QT_CONFIG(tooltip)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
#if QT_CONFIG(tooltip)
        self.actionPreferences.setToolTip(QCoreApplication.translate("MainWindow", u"Application parameters adjustment", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionPreferences.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionTestInformation.setText(QCoreApplication.translate("MainWindow", u"Step &Information", None))
#if QT_CONFIG(tooltip)
        self.actionTestInformation.setToolTip(QCoreApplication.translate("MainWindow", u"Details on the selected test step", None))
#endif // QT_CONFIG(tooltip)
        self.checkSelect.setText(QCoreApplication.translate("MainWindow", u"Select all / deselect all", None))
        self.checkFold.setText(QCoreApplication.translate("MainWindow", u"Fold / Unfold", None))
        self.label_runtime.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.buttBlink.setText("")
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuTest.setTitle(QCoreApplication.translate("MainWindow", u"&Test", None))
        self.menuA_propos.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.logDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Log", None))
        self.buttLogFileNone.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.buttLogFileSaved.setText(QCoreApplication.translate("MainWindow", u"To file", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Log file path", None))
        self.buttLogFilePath.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Log View", None))
#if QT_CONFIG(tooltip)
        self.buttClearLog.setToolTip(QCoreApplication.translate("MainWindow", u"Clear the log view", None))
#endif // QT_CONFIG(tooltip)
        self.buttClearLog.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.buttGoBottom.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Uncheck this button to browse back the log</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.buttGoBottom.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.DocDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Test doc", None))
    # retranslateUi

