
#****************************************************************************
#    Test configuration
#**************************************************************************** -->
windows_prompt: >
linux_prompt: $
sequence: tm.tum

# loops parameters
global_loop_param_list: [["one", "two", "three"], [1, 2, 3]]
global_loop_param_txt: ['one', 'two', 'three']
global_loop_param_num: [1, 2, 3]

# Plot parameters
plot_log_path: /tmp/testium_plot/$(testrun_date)/$(testrun_time)/

python_path_Windows: C:\Users\François\Applications\Python313\python.exe
python_path_Linux: $(home)/tmp/tum_venv/bin/python3

