
#****************************************************************************
#    Test configuration
#**************************************************************************** -->
# loops parameters
global_loop_param_txt: ['one', 'two', 'three']
global_loop_param_num: [1, 2, 3]

# Plot parameters
plot_log_path: /tmp/testium_plot/$(testrun_date)/$(testrun_time)/

python_path: $(home)/tmp/tum_venv/bin/python3

lua_path: /usr/bin/lua
lua_env:
  LUA_PATH: /usr/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;/usr/lib/lua/5.4/?.lua;/usr/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/home/francois/.luarocks/share/lua/5.4/?.lua;/home/francois/.luarocks/share/lua/5.4/?/init.lua
  LUA_CPATH: /usr/local/lib/lua/5.4/?.so;/usr/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/loadall.so;/usr/lib/lua/5.4/loadall.so;./?.so;/home/francois/.luarocks/lib/lua/5.4/?.so
